# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

# NOTE - you need to install
# - http://forge.puppetlabs.com/puppetlabs/stdlib
# - https://forge.puppetlabs.com/puppetlabs/mysql
# - https://forge.puppetlabs.com/spiette/selinux
# 
# After the initial provisioning the VM needs to be rebooted 
# once to disable selinux

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "fedora-18-x65-vbox4120"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  config.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/fedora-18-x64-vbox4210.box"

  config.vm.network :forwarded_port, guest: 5040, host: 5040
  
  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "manifests"
    puppet.manifest_file  = "site.pp"
    puppet.module_path = ["modules", "/etc/puppet/modules"]
  end
end
